<?xml version="1.0"?>
<gazebo:world
  xmlns:xi="http://www.w3.org/2001/XInclude"
  xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
  xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
  xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
  xmlns:window="http://playerstage.sourceforge.net/gazebo/xmlschema/#window"
  xmlns:param="http://playerstage.sourceforge.net/gazebo/xmlschema/#param"
  xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
  xmlns:geo="http://willowgarage.com/xmlschema/#geo"
  xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
  xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
  xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
  xmlns:ui="http://playerstage.sourceforge.net/gazebo/xmlschema/#ui"
  xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
  xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
  xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
  xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics"
  xmlns:xacro="http://www.ros.org/wiki/xacro"
  >


  <!-- ============================ -->
  <!-- BEGIN XACRO DEFINITIONS      -->
  <!-- ============================ -->

  <!-- Ground plane size in metres (both x and y) -->
  <xacro:property name="GROUND_PLANE_SIZE"  value="100.0" />

  <!-- Range and height for each light -->
  <xacro:property name="LIGHT_RANGE"        value="${GROUND_PLANE_SIZE/4}" />
  <xacro:property name="LIGHT_HEIGHT"       value="10.0" />

  <!-- Macro to create one point light at given position -->
  <xacro:macro name="LIGHT_MACRO" params="n x y z">
    <model:renderable name="light_${n}">

      <!-- Affected by gravity -->
      <enableGravity>false</enableGravity>

      <!-- Light pose (only needed for point or spot) -->
      <xyz>${x} ${y} ${z}</xyz>
      <rpy>0.0 0.0 0.0</rpy>

      <!-- Light parameters -->
      <light>

        <!-- Light type (point, directional, or spot) -->
        <type>point</type>

        <!-- Light direction vector (only for directional or spot) -->
        <direction>0.0 0.0 -1.0</direction>

        <!-- Spotlight parameters (only for spot) -->
        <innerAngle>10.0</innerAngle>
        <outerAngle>20.0</outerAngle>
        <falloff>1.0</falloff>

        <!-- Cast shadows -->
        <castShadows>true</castShadows>

        <!-- Diffuse colour (matte surfaces) in RGB ([0,1]) -->
        <diffuseColor>0.8 0.8 0.8</diffuseColor>

        <!-- Specular colour (glossy surfaces) in RGB ([0,1]) -->
        <specularColor>0.1 0.1 0.1</specularColor>

        <!-- Attenuation over range (constant, linear, quadratic) -->
        <attenuation>0.2 0.1 0.0</attenuation>

        <!-- Light range (m) -->
        <range>${LIGHT_RANGE}</range>
      </light>
    </model:renderable>
  </xacro:macro>

  <!--
    Macro to create point lights distributed around the world.  This is just an easy way to get
    light everwhere.  If we could spawn lights we might choose to spawn lights as needed instead.
  -->
  <xacro:macro name="LIGHTS_MACRO">
    <xacro:LIGHT_MACRO n="1" x="0"                y="0"               z="${LIGHT_HEIGHT}" />
    <xacro:LIGHT_MACRO n="2" x="${LIGHT_RANGE}"   y="${LIGHT_RANGE}"  z="${LIGHT_HEIGHT}" />
    <xacro:LIGHT_MACRO n="3" x="${LIGHT_RANGE}"   y="-${LIGHT_RANGE}" z="${LIGHT_HEIGHT}" />
    <xacro:LIGHT_MACRO n="4" x="-${LIGHT_RANGE}"  y="${LIGHT_RANGE}"  z="${LIGHT_HEIGHT}" />
    <xacro:LIGHT_MACRO n="5" x="-${LIGHT_RANGE}"  y="-${LIGHT_RANGE}" z="${LIGHT_HEIGHT}" />
  </xacro:macro>

  <!-- ============================ -->
  <!-- END XACRO DEFINITIONS        -->
  <!-- ============================ -->

  <!-- General -->
  <thread>4</thread>
  <verbosity>5</verbosity>

  <!-- Physics -->
  <physics:ode>

    <!-- Gravity (m/s^2) -->
    <gravity>0.0 0.0 -9.8</gravity>

    <!-- Physics engine step duration (s) -->
    <stepTime>0.001</stepTime>

    <!-- Physics engine step parameters -->
    <stepType>quick</stepType>
    <stepIters>10</stepIters>
    <stepW>1.3</stepW>

    <!-- Physics engine speed (<0: real time, 0: max, >0: stepTime*this -->
    <updateRate>-1</updateRate>

    <!-- Constraint force mixing (stiffness) -->
    <cfm>1e-10</cfm>

    <!-- Error reduction parameter (damping) -->
    <erp>0.2</erp>

    <!-- Maximum velocity that a contact can generate (m/s) -->
    <contactMaxCorrectingVel>10.0</contactMaxCorrectingVel>

    <!-- Depth to which contacts may sink (m) -->
    <contactSurfaceLayer>0.005</contactSurfaceLayer>

  </physics:ode>

  <!-- Geographical origin -->
  <geo:origin>
    <lat>43.24355</lat>
    <lon>-5.776711</lon>
  </geo:origin>

  <!-- GUI -->
  <rendering:gui>
    <!-- GUI type, for now only fltk exists -->
    <type>fltk</type>

    <!-- GUI window size -->
    <size>480 320</size>

    <!-- GUI window position -->
    <pos>0 0</pos>

    <!-- GUI frames loaded initially -->
    <frames>
      <row height="100%">
        <camera width="100%">
          <xyz>0 0 10</xyz>
          <rpy>0 90 90</rpy>
        </camera>
      </row>
    </frames>
  </rendering:gui>

  <!-- Rendering settings -->
  <rendering:ogre>
    <!-- Ambient light -->
    <ambient>0.4 0.4 0.4 0.4</ambient>
    <sky>
      <material>Gazebo/CloudySky</material>
    </sky>
    <grid>false</grid>
    <maxUpdateRate>10</maxUpdateRate>
    <shadowTechnique>none</shadowTechnique>
    <shadows>false</shadows>
  </rendering:ogre>

  <!-- Ground -->
  <model:physical name="ground">
    <xyz>0.0 0.0 0.0</xyz>
    <rpy>0.0 0.0 0.0</rpy>
    <static>true</static>
    <body:plane name="ground_body">
      <geom:plane name="ground_geom">
        <laserRetro>2000.0</laserRetro>
        <mu1>50.0</mu1>
        <mu2>50.0</mu2>
        <kp>1000000000.0</kp>
        <kd>1.0</kd>
        <normal>0.0 0.0 1.0</normal>
        <size>${GROUND_PLANE_SIZE} ${GROUND_PLANE_SIZE}</size>
        <segments>10 10</segments>
        <uvTile>${GROUND_PLANE_SIZE} ${GROUND_PLANE_SIZE}</uvTile>
        <material>Gazebo/GrayGrid</material>
      </geom:plane>
    </body:plane>
  </model:physical>

  <!-- Lights -->
  <xacro:LIGHTS_MACRO/>

</gazebo:world>
